// src/components/Title.svelte
<script lang="ts">
	export let level: '1' | '2' | '3' | '4' = '1';
	export let style: 'light' | null = null;

	const Tag = `h${level}` as HTMLElement;
	const Style = style;
</script>

<svelte:element this={Tag} class={Style}>
  <slot />
</svelte:element>

<style>
	h2 {
		margin: 0 0 20px 0;
		padding: 0;
		color: #c91010;
		font: var(--font-title-h2);
	}

	h2:not(:first-of-type) {
		margin-top: 20px;
	}

	h2.light {
		margin: 0 0 20px 0;
		padding: 0;
		color: #c91010;
		font: var(--font-title-h2-light);
	}

	h3 {
		font: var(--font-title-h3);
		margin: 0 0 8px 0;
		letter-spacing: calc(1px / 5);
	}

	h3:not(:first-of-type) {
		margin-top: 5px;
	}

	h4 {
		margin: 0 0 20px 0;
		padding: 0;
		color: #c91010;
		font: var(--font-title-h4);
	}
</style>

// components/Title.vue
<template>
  <component :is="htmlTag" :class="`title--h${level}`">
    <slot />
  </component>
</template>

<script lang="ts">
import Vue from 'vue'

export default Vue.extend({
  props: {
    level: {
      type: String,
      default: '2'
    }
  },
  computed: {
    htmlTag () {
      return `h${this.level}`
    }
  }
})
</script>

<style>
  .title--h2 {
    margin: 0 0 20px 0;
    padding: 0;
    color: #c91010;
    font: 300 20px IBM Plex Sans, sans-serif;
  }
</style>
