// src/components/Container.svelte
<script lang="ts">
	export const size: '1200' | '800' | null = '1200';

	let cssClass = `container--${size}`;
</script>

<div class={cssClass}>
	<slot />
</div>

<style>
	.container--1200 {
		max-width: 1200px;
		width: 100%;
		margin: 50px auto 20px auto;
		padding: 0 10px;
	}

	@media only screen and (max-width: 595px) {
		.container--1200 {
			padding: 0 10px;
		}
	}

	.container--800 {
		max-width: 800px;
	}
</style>

// components/container/Container.vue
<template>
  <div :class="cssClass">
    <slot />
  </div>
</template>

<script lang="ts">
import Vue from 'vue'

export default Vue.extend({
  props: {
    type: {
      type: String,
      default () {
        return null
      }
    }
  },
  computed: {
    cssClass () {
      return `container_${this.type}`
    }
  }
})
</script>

<style>
  .container_common {
    max-width: 1200px;
    width: 100%;
    margin: 0 auto 20px auto;
    padding: 50px 10px 0 10px;
  }

  .container_content {
    max-width: 800px;
  }
</style>
